{{- if .Values.service -}}
{{- if .Values.service.required }}
{{- if .Values.service.autoscaling }}
{{- if .Values.service.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "api.fullname" . }}-hpa
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "api.fullname" . }}
  minReplicas: {{ .Values.service.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.service.autoscaling.maxReplicas }}
  metrics:
    {{- if .Values.service.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ .Values.service.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if .Values.service.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ .Values.service.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
  {{- if .Values.service.autoscaling.behavior }}
  behavior:
    {{- toYaml .Values.service.autoscaling.behavior | nindent 4 }}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
