{{- if .Values.service -}}
{{- if .Values.service.required -}}
{{- if .Values.service.gateway }}
{{- if .Values.service.gateway.required -}}
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceIntentions
metadata:
  name: {{ include "api.fullname" . }}-service-intentions
spec:
  destination:
    name: {{ include "api.fullname" . }}
  sources:
    - name: {{ .Values.service.gateway.name }}
      action: allow
{{- end }}
{{- end }}
{{- end }}
{{- end }}