{{- if .Values.service -}}
{{- if .Values.service.serviceAccount -}}
{{- if .Values.service.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "api.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "api.labels" . | nindent 4 }}
  {{- with .Values.service.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
automountServiceAccountToken: {{ .Values.service.serviceAccount.automount }}
{{- end }}
{{- end }}
{{- end }}
