{{- if .Values.service -}}
{{- if .Values.service.required -}}
{{- if .Values.service.gateway }}
{{- if .Values.service.gateway.required -}}
apiVersion: consul.hashicorp.com/v1alpha1
kind: ServiceDefaults
metadata:
  name: {{ include "api.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  protocol: "http"
{{- end }}
{{- end }}
{{- end }}
{{- end }}
